AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ApiGatewayCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: api.rocketgeek.org
      DomainNameConfigurations:
        - CertificateArn: arn:aws:acm:REGION:ACCOUNT_ID:certificate/CERTIFICATE_ID
          EndpointType: REGIONAL

  ApiGatewayDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: rocketgeek.org.
      Name: api.rocketgeek.org
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiGatewayCustomDomain.RegionalDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # Standard Hosted Zone ID for API Gateway Regional endpoints
      Comment: "API Gateway Custom Domain for api.rocketgeek.org"

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: api.rocketgeek.org
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: api.rocketgeek.org
          HostedZoneId: Z06404632JRVK1UWCONYE

Outputs:
  ApiGatewayDNS:
    Value: !Ref ApiGatewayDNSRecord
    Description: "DNS record for the API Gateway at api.rocketgeek.org"
